-- Create demo auth users through Supabase Studio/Auth first, then replace these UUIDs.
-- This seed intentionally contains no passwords or production credentials.
-- Example tasks are generated by scripts/seed-demo.sql after IDs are configured.
select 'Create Owner, Plant Head, and Accountant in Authentication > Users, then update their profiles.' as next_step;
