"use client";
import { useMemo,useState } from "react";
import { Bell,Check,ChevronRight,ClipboardList,LayoutDashboard,Menu,Plus,Search,Sunrise,Users,X } from "lucide-react";
import { isOverdue,statusLabel,type Priority,type Task } from "@sunrise/shared";
import { useApp } from "./app-provider";
import { TaskDetail } from "./task-detail";
import { NewTask } from "./new-task";

type Filter="all"|"new"|"unacknowledged"|"in_progress"|"overdue"|"completed";
export function Dashboard(){
 const {tasks}=useApp(); const [filter,setFilter]=useState<Filter>("all"); const [priority,setPriority]=useState<"all"|Priority>("all"); const [search,setSearch]=useState(""); const [selected,setSelected]=useState<Task>(); const [creating,setCreating]=useState(false); const [menu,setMenu]=useState(false);
 const count=(f:Filter)=>tasks.filter(t=>f==="all"?true:f==="overdue"?isOverdue(t):f==="unacknowledged"?t.status==="new":t.status===f).length;
 const visible=useMemo(()=>tasks.filter(t=>(filter==="all"||filter==="overdue"&&isOverdue(t)||filter==="unacknowledged"&&t.status==="new"||t.status===filter)&&(priority==="all"||t.priority===priority)&&(`${t.title} ${t.description} ${t.assignedName}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>Number(isOverdue(b))-Number(isOverdue(a))||({urgent:0,high:1,normal:2}[a.priority]-{urgent:0,high:1,normal:2}[b.priority])||a.dueDate.localeCompare(b.dueDate)),[tasks,filter,priority,search]);
 return <div className="shell">
  <aside className={menu?"sidebar open":"sidebar"}><div className="brand"><span className="brandmark"><Sunrise size={24}/></span><div>Sunrise <b>Tasks</b></div><button className="icon mobile" onClick={()=>setMenu(false)}><X/></button></div><nav><button className="active"><LayoutDashboard/>Dashboard</button><button><ClipboardList/>Tasks</button><button><Users/>Users</button></nav><div className="sidebar-foot"><span className="avatar">VM</span><div><b>Vikram Mehta</b><small>Owner / Admin</small></div></div></aside>
  <main><header><button className="icon mobile" onClick={()=>setMenu(true)}><Menu/></button><div><h1>Good morning, Vikram</h1><p>Here’s what needs attention at Sunrise today.</p></div><div className="header-actions"><button className="bell"><Bell/><span>3</span></button><button className="primary" onClick={()=>setCreating(true)}><Plus/>New Task</button></div></header>
  <section className="content"><div className="stats">
   <Stat label="New" value={count("new")} tone="blue" onClick={()=>setFilter("new")}/><Stat label="Unacknowledged" value={count("unacknowledged")} tone="amber" onClick={()=>setFilter("unacknowledged")}/><Stat label="In progress" value={count("in_progress")} tone="purple" onClick={()=>setFilter("in_progress")}/><Stat label="Overdue" value={count("overdue")} tone="red" onClick={()=>setFilter("overdue")}/><Stat label="Completed" value={count("completed")} tone="green" onClick={()=>setFilter("completed")}/>
  </div><div className="panel"><div className="panel-head"><div><h2>All tasks</h2><p>{visible.length} tasks shown</p></div><div className="tools"><label className="search"><Search/><input aria-label="Search tasks" placeholder="Search tasks or people" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Priority" value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}><option value="all">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option></select></div></div>
   <div className="filters">{(["all","new","unacknowledged","in_progress","overdue","completed"] as Filter[]).map(f=><button className={filter===f?"selected":""} onClick={()=>setFilter(f)} key={f}>{f.replace("_"," ")} <span>{count(f)}</span></button>)}</div>
   <div className="task-table"><div className="table-header"><span>Task</span><span>Assigned to</span><span>Priority</span><span>Status</span><span>Due</span><span>Latest update</span><span/></div>{visible.map(t=><TaskRow key={t.id} task={t} onClick={()=>setSelected(t)}/>)}</div>{!visible.length&&<div className="empty"><Check/><h3>You’re all caught up</h3><p>No tasks match these filters.</p></div>}
  </div></section></main>{creating&&<NewTask onClose={()=>setCreating(false)}/>} {selected&&<TaskDetail task={tasks.find(t=>t.id===selected.id)!} onClose={()=>setSelected(undefined)}/>}</div>
}
function Stat({label,value,tone,onClick}:{label:string;value:number;tone:string;onClick:()=>void}){return <button className={`stat ${tone}`} onClick={onClick}><span>{label}</span><strong>{value}</strong><small>View tasks <ChevronRight/></small></button>}
function TaskRow({task,onClick}:{task:Task;onClick:()=>void}){const overdue=isOverdue(task);return <button className={`task-row ${task.status==="completed"?"done":""}`} onClick={onClick}><span className="task-name"><i className={`dot ${task.priority}`}/><span><b>{task.title}</b><small>{task.id}</small></span></span><span className="person"><i>{task.assignedName.split(" ").map(x=>x[0]).join("")}</i>{task.assignedName}</span><span><em className={`priority ${task.priority}`}>{task.priority}</em></span><span><em className={`status ${task.status}`}>{statusLabel(task.status)}</em></span><span className={overdue?"due overdue":"due"}>{overdue&&<b>OVERDUE</b>}{new Date(task.dueDate+"T12:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short"})}{task.dueTime&&`, ${task.dueTime}`}</span><span className="latest">{task.latestUpdate||"No update yet"}</span><ChevronRight/></button>}
