import type { Profile, Task, TimelineItem } from "@sunrise/shared";
const today = new Date();
const date=(offset:number)=>{ const d=new Date(today); d.setDate(d.getDate()+offset); return d.toISOString().slice(0,10) };
export const owner:Profile={id:"a4e2b7e7-4dcc-4e8f-b85f-e0127407e776",fullName:"Vikram Mehta",email:"owner@sunrise.demo",role:"admin",department:"Owner",active:true};
export const people:Profile[]=[owner,{id:"b13d31f7-a99f-4a14-9874-1e42b57a7b51",fullName:"Rajesh Sharma",email:"rajesh@sunrise.demo",role:"employee",department:"Plant Head",active:true},{id:"17c6c88c-1996-49bb-a6ec-d5faea8722e8",fullName:"Amit Gupta",email:"amit@sunrise.demo",role:"employee",department:"Accounts",active:true},{id:"39bddc68-e37e-49d5-b26f-f76d44118a38",fullName:"Neha Verma",email:"neha@sunrise.demo",role:"employee",department:"Dispatch",active:true}];
const base={createdBy:owner.id,createdByName:"Vikram Mehta",createdAt:new Date(Date.now()-86400000).toISOString(),updatedAt:new Date(Date.now()-1800000).toISOString()};
export const initialTasks:Task[]=[
 {id:"ST-1048",title:"Check HDPE raw material stock",description:"Check the current physical stock and report whether additional material needs to be ordered.",assignedTo:people[1]!.id,assignedName:"Rajesh Sharma",priority:"urgent",status:"in_progress",dueDate:date(0),dueTime:"17:00",latestUpdate:"Physical stock count completed. 650 kg available.",acknowledgedAt:new Date(Date.now()-7200000).toISOString(),startedAt:new Date(Date.now()-6500000).toISOString(),...base},
 {id:"ST-1049",title:"Confirm August GST payment",description:"Verify the payment amount and confirm filing status.",assignedTo:people[2]!.id,assignedName:"Amit Gupta",priority:"high",status:"new",dueDate:date(1),...base},
 {id:"ST-1046",title:"Inspect cap moulding machine #2",description:"Machine is making an unusual sound during the second shift.",assignedTo:people[1]!.id,assignedName:"Rajesh Sharma",priority:"urgent",status:"acknowledged",dueDate:date(-1),dueTime:"16:00",acknowledgedAt:new Date(Date.now()-3600000).toISOString(),...base},
 {id:"ST-1045",title:"Share weekly dispatch report",description:"Send customer-wise dispatch totals.",assignedTo:people[3]!.id,assignedName:"Neha Verma",priority:"normal",status:"completed",dueDate:date(-1),completedAt:new Date(Date.now()-5400000).toISOString(),latestUpdate:"Report shared with owner.",...base},
 {id:"ST-1050",title:"Count 50gm powder caps",description:"Complete a physical count in finished goods storage.",assignedTo:people[1]!.id,assignedName:"Rajesh Sharma",priority:"normal",status:"new",dueDate:date(2),...base}
];
export const initialTimeline:TimelineItem[]=[{id:"h1",taskId:"ST-1048",authorName:"Vikram Mehta",kind:"event",message:"Task created and assigned to Rajesh Sharma",createdAt:new Date(Date.now()-86400000).toISOString()},{id:"h2",taskId:"ST-1048",authorName:"Rajesh Sharma",kind:"event",message:"Acknowledged the task",createdAt:new Date(Date.now()-7200000).toISOString()},{id:"h3",taskId:"ST-1048",authorName:"Rajesh Sharma",kind:"event",message:"Started working",createdAt:new Date(Date.now()-6500000).toISOString()},{id:"h4",taskId:"ST-1048",authorName:"Rajesh Sharma",kind:"update",message:"Physical stock count completed. 650 kg available.",createdAt:new Date(Date.now()-1800000).toISOString()}];
